- import_playbook: playbooks/deploy-common.yml
- import_playbook: playbooks/checkout.yml
- import_playbook: playbooks/deploy-site.yml
- import_playbook: playbooks/deploy-nginx.yml
- import_playbook: playbooks/deploy-lb.yml
#- import_playbook: playbooks/deploy-firewall.yml